Tweet t1 = new Tweet("Hi folks! This is the beta test of the new twitter reborn in Groovy!!!")
t1.publish()
t1.printComments()
t1.addComment("hey man, that's awesome!!!")
t1.addComment("alright man, let's see some more!!!")
t1.addComment("what a load of crap man !!!")
t1.printComments()